language: java
 
env:
  global:
    - SONATYPE_USERNAME=chicchiricco
    - secure: "RO+CXEuJPYgTpndr5JjysAv5MulRbMmkUHQQJZ9Hl68qM2T43+X8E2fzGMPU8gaU/A33BzSi+CYZol8wcP8KVy9+kKa2xD5zovRXMrFHgb5ZpUINwgF4wDsJcc/QxULPorx60hOwxpiutpJ3Z3v21NdMGiyDlcv6a808984C5YjeTinRndMIxiF3PNiMOgnIXr7yo2GvLdqVpc34+UlbfNEWQDbeTyiRC2gabnMGJPSGCdTU21WtxzFo0ucLsttOFsg1Fh83W26LI+jHgdG5lzIzlAOEY+iyXE+8DNfnxQSFMFmWkBvT9vKuap96QmTfWLWdjIuJA0XoPOhJ2FBkdwZ0/nf+3AQ7mcnWqz4t/bcME6ftipC71MxeAv7zMKf7WyyF8E8c2gedJ59I2t8ddzqOE7ZD3qS8oUY29ImRSwPadQPJxnTFDMOztqExYeqwN50n2wQwykbZQaCFuyGNF3pj6HvyacriNQ424aQeNtT8HuRyMu/3CaRiq60QSIzZxvKTz6knBWT5WThsLjcpjtjYOcVujItemnY6B74+3r07YlMU1srn2SrTXO653Dkuh32s0Q509neeo0ByQPYsIuqdmVK+iSQd00hbgX1eA5K4PnEYsgWN94I6RaeviVnkZjVlX1IfKr2x1dHREZVnvDaMIlGsuR+PTvoc7OALFTs="

after_success:
  - python .travis.addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml

notifications:
  email:
    - connid-dev@googlegroups.com
